### ISSUE TITLE
Validation Test for new builds 

### ISSUE THREAD

**Issue by voatsap** [shalb/cluster.dev#12]
In order to be sure that merges which are coming to master does not broke main scenario, we need validation env job.
Idea to spawn a new cluster each commit in PR for feature or in Master branch and run validation test.
As for now we could test that ArgoCD is available for login. 
In future version we'd like to be sure that example application was deployed to cluster and passes required health checks

**Comment by romanprog** [comment]
Validation tests added for new version.
