### ISSUE TITLE
Add possibility to specify subnet-id

### ISSUE THREAD

**Issue by MaxymVlasov** [shalb/cluster.dev#14]
By default, `vpc_id` - empty, and this part of condition works fine
But when anyone set custom `vpc_id`, why it always must be 1-st in subnets? Maybe we also should add possibility to specify `subnet-id`, because in vpc can be subnets w/o access to external (internet) resources and cluster creation will failed

More context: https://github.com/shalb/cluster.dev/pull/8#discussion_r380124952

**Comment by voatsap** [comment]
To be Resolved by https://github.com/shalb/cluster.dev/pull/67/commits/af6b036a82c6e87480a1c934f0173f2e5492abc5

**Comment by voatsap** [comment]
Resolved
