### ISSUE TITLE
Create default subzone for new cluster 

### ISSUE THREAD

**Issue by MaxymVlasov** [shalb/cluster.dev#2]
Create  service that add new subzone (UserID.cluster.dev) for all new clusters by POST request.

1. Create subzone by TF in user account 
2. Get NS from output and send to cluster.dev API Gateway
3. API Gteway triggers Lambda 
4. Lambda add NS record that point to user NS'es from step 2.

**Comment by voatsap** [comment]
Discussed with @gelo22 
Lambda workflow:
POST (Action(CREATE/UPDATE/DELETE), UserName, NS Servers, ZoneID) -> API Gateway -> Triggers Lambda (R53 record NS user-gh.cluster.dev) -> POST (DynamoDB).

**Comment by gelo22** [comment]
What is done:
Route53 management via POST request(json)
Example for my test tomain:
```
event['body'] = {
    "Action": "CREATE|DELETE|UPDATE",
    "UserName": "gelo22",
    "NameServers": "ns-1768.awsdns-29.co.uk.,ns-683.awsdns-21.net.,ns-484.awsdns-60.com.,ns-1156.awsdns-16.org.",
    "ZoneID": "Z0978963ADA7KRYE5RPL",
    "DomainName": "test-domain.fun"
}
```

TODO:
Use some naming rules for resources.
Add tags for Route53 records if possible(DomainName).
Use DynamoDB as records storage
Write terraform(version12) code to deploy all things to aws
Add Cloudwatch alerting for lambda, integrate with Opsgenie

**Comment by gelo22** [comment]
https://github.com/shalb/cluster.dev-domain/pull/1

TODO:
Lambda:
- Add tags for Route53 records if possible(DomainName).
- Add source IP and modification time of record to each record
Cloudwatch:
- Add alerting for lambda, integrate with Opsgenie
Terraform:
Add code to:
- import certificate
- deploy "Custom domain" (link with mentioned certificate)
- link "Custom domain" with API gateway
- Add route53 record
Docs:
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-regional-api-custom-domain-create.html
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-api-gateway.html#routing-to-api-gateway-config

**Comment by voatsap** [comment]
cluster-dev support for domains merged:
https://github.com/shalb/cluster.dev/pull/60

**Comment by voatsap** [comment]
close due inaction.
Base functions works as expected.
