### ISSUE TITLE
Unsolicited emails using information scraped from GitHub is against GitHub ToS

### ISSUE THREAD

**Issue by Xerkus** [shalb/cluster.dev#249]
> Hey there, I saw that you gave a star to the Atlantis repository on Github and thought you might be interested in discovering some other cool tools. I recently launched Cluster.dev, an open-source templating engine for simplifying software deployment across different cloud platforms. Your thoughts and feedback would be incredibly valuable in shaping its development.

No consent were given. Please cease and desist.

**Comment by arcanemachine** [comment]
The marketing email uses Mailchimp (URL starts with `https://shalb.us11.list-manage.com/`). Make sure to forward the spam email to `abuse@mailchimp.com`.

https://mailchimp.com/contact/abuse/

---

Mailchimp Terms Of Service:

https://mailchimp.com/legal/terms/

>  IV. Rules and abuse
> 
> 18. General Rules
> 
> By agreeing to these Terms, you promise to follow these rules:
> 
>   1. You won’t send spam!

**Comment by clusterdev-agent** [comment]
Hello,

My name is Oleksandr. I am a marketer manager at Cluster.dev. I'm sorry for the trouble. We want you to know that our intentions are purely professional, and we didn't mean to disturb you. We found your contact in your profile description. 

We found your expertise impressive in this case, so we wanted to ask your opinion about our solutions... I apologize again for the confusion. You will no longer receive emails from us.

**Comment by clusterdev-agent** [comment]
> > Hey there, I saw that you gave a star to the Atlantis repository on Github and thought you might be interested in discovering some other cool tools. I recently launched Cluster.dev, an open-source templating engine for simplifying software deployment across different cloud platforms. Your thoughts and feedback would be incredibly valuable in shaping its development.
> 
> No consent were given. Please cease and desist.

Hello,

My name is Oleksandr. I am a marketer manager at Cluster.dev. I'm sorry for the trouble. We want you to know that our intentions are purely professional, and we didn't mean to disturb you. We found your contact in your profile description.

We found your expertise impressive in this case, so we wanted to ask your opinion about our solutions... I apologize again for the confusion. You will no longer receive emails from us.

**Comment by Xerkus** [comment]
None of those contacted using collected contact information should receive emails again.

You performed ethically questionable action by collecting said contact information from those who did not interact with you in any way. Information being in public access does not provide blanket permission to use it for any purpose.

GitHub user's emails are only accessible to authenticated users. Authenticated users agreed to Terms of Service and Acceptable Use Policy and must abide by them.

I refer you to GitHub Acceptable Use Policy, [Information Usage Restrictions](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies#7-information-usage-restrictions)

> You may not use information from the Service (whether scraped, collected through our API, or obtained otherwise) for spamming purposes, including for the purposes of sending unsolicited emails to users or selling personal information, such as to recruiters, headhunters, and job boards.

I do not believe this was a malicious act. Should it have been I would have resorted to reporting it to GitHub. Nevertheless it is not acceptable.

I understand that mistakes happen. I trust you will avoid it in the future.

Please convert this issue to a discussion. I did not notice discussions were enabled.

**Comment by orbitz** [comment]
Very unacceptable behaviour in scraping my contact information from GitHub.  Responding with some bullshit about "your expertise was impressive" is uncouth.  Just say you're sorry, delete our emails, and move on.

**Comment by voatsap** [comment]
Issue not related to product technical implementation. Replies provided by Oleksandr @clusterdev-agent, closing issue.
