### ISSUE TITLE
[Feature] Passing variables and outputs between different projects

### ISSUE THREAD

**Issue by kinseii** [shalb/cluster.dev#253]
**What would you like to add**
I really enjoyed the project, looking forward to implementing this in our fifty+ environments. However, the only thing stopping me is the fact that we won't be able to pass variables and outputs (Such as similar functions of terragrunt: `read_terragrunt_config` and `dependency`) between projects. Please provide such a feature.

**Comment by voatsap** [comment]
@kinseii thanks for proposal we are checking posibility of this feature, woud back in short time about it.

**Comment by kinseii** [comment]
OK, we'll try to do it as part of the project.
