### ISSUE TITLE
Display all outputs of the `tfmodule` unit in the `printer` unit without specifying them

### ISSUE THREAD

**Issue by kinseii** [shalb/cluster.dev#256]
**What would you like to add**
Is it possible to make it so that all outputs of a tfmodule unit can be displayed in a printer's unit without specifying a particular output key?

**Why is this needed**
We don't want to copy the terraform module outputs code into the cluster.dev template, respecting the DRY principle.

**Comment by kinseii** [comment]
This seems to be irrelevant, I've figured out how to handle the remoteState reference and it doesn't give code repetition.

**Comment by romanprog** [comment]
> This seems to be irrelevant, I've figured out how to handle the remoteState reference and it doesn't give code repetition.

To some extent, this request is relevant. We decided that remoteState should be able to broadcast output. But I will open a new feature request for this with a more detailed description.
 Thank you.
