### ISSUE TITLE
Implement an analog of the `templatefile` terraform function

### ISSUE THREAD

**Issue by kinseii** [shalb/cluster.dev#258]
**What would you like to add**
I want to use templating inside files, to substitute variable values, like the `templatefile` function in terraform does.

**Why is this needed**
This is necessary for templating the .yaml files of `helm` and `k8s-manifest` units.

This issue may have a connection to the issue at hand: https://github.com/shalb/cluster.dev/issues/225

P.S.
Also, I don't understand what the `apply_template` option of the `helm` unit means? Can you clarify it here and add it to the documentation?

**Comment by kinseii** [comment]
It seems to be irrelevant, I figured out how to work with templates, it's similar to helm templates, obviously because of the development language go.

**Comment by romanprog** [comment]
> It seems to be irrelevant, I figured out how to work with templates, it's similar to helm templates, obviously because of the development language go.

Also looks like a duplicate of ticket https://github.com/shalb/cluster.dev/issues/225
It will be possible to read and apply the template to the files. The feature will be added in the next releases.
