### ISSUE TITLE
Ignoring processing of specified `.yaml` files

### ISSUE THREAD

**Issue by kinseii** [shalb/cluster.dev#259]
**What would you like to add**
Need option to ignore files with extension `.yml` and `.yaml`. Maybe do this via pointing to the `.cdevignore` file, as is done in `.gitignore` and `.dockerignore`.

**Why is this needed**
I added `.gitlab-ci.yml` and `.pre-commit-config.yaml` to the repository with `.yaml` files cluster.dev and cdev gives an error:
```
[FATAL] Fatal error: load project configuration: read objects: object must contain field 'kind'
```

**Comment by romanprog** [comment]
@kinseii added `.cdevignore` 
The `.cdevignore` file is used to specify files that you don't want to be read as project/stacktemplate configs. With this file in the `project` dir and in the `stackTemplate` dir, cdev will ignore the list of specified yaml/yml files as it configs. These files should be specified as a list of full names. Templates and patterns are not supported. Example of the `.cdevignore` file:

```
deployment.yaml
foo.yml
bar.yaml
```
https://github.com/shalb/cluster.dev/releases/tag/v0.9.4

**Comment by kinseii** [comment]
Checked, it works!
