### ISSUE TITLE
Installed: true/false, deploy nginx-ingress addon in entrypoint script, destroy procedure 

### ISSUE THREAD

**Issue by romanprog** [shalb/cluster.dev#26]
Take kubernetes addons installation in a separate step (deploy nginx-ingress addon in entrypoint script). 
Installed: true/false and destroy procedure
tests fixes

**Comment by MaxymVlasov** [comment]
Destroying of 
- S3
- DynamoDB 
- Route53 
can be done as part of this issue or you can open new
https://github.com/shalb/cluster.dev/pull/28#issuecomment-601146795

**Comment by romanprog** [comment]
> Destroying of
> 
> * S3
> * DynamoDB
> * Route53
>   can be done as part of this issue or you can open new
>   [#28 (comment)](https://github.com/shalb/cluster.dev/pull/28#issuecomment-601146795)
@MaxymVlasov 
S3 - done
DynamoDB - done
Route53 - what exactly route53 records? Function aws::init_route53 is empty now.

**Comment by romanprog** [comment]
tested and merged
