### ISSUE TITLE
Function `validate`

### ISSUE THREAD

**Issue by kinseii** [shalb/cluster.dev#274]
**What would you like to add**
The `cdev validate` function is required to fully validate the cdev configuration.

**Why is this needed**
Now to check the configuration, I have to run the `cdev plan` command that tries to operate on the state files. I need a check function without having to get the state files.

**Comments**
IIt could be like: `terraform validate`, `terragrunt validate` commands.

**Comment by romanprog** [comment]
https://github.com/shalb/cluster.dev/releases/tag/v0.9.5
released in 0.9.5
Also you can use `cdev project info` for validation. This command prints full info about project.

**Comment by kinseii** [comment]
OMG! This is awesome! Very quick realization! Impressed! Thank u so much @romanprog!

**Comment by romanprog** [comment]
> OMG! This is awesome! Very quick realization! Impressed! Thank u so much @romanprog!

It was very simple to implement and there have been similar requests before.
