### ISSUE TITLE
A hyphen in a variable causes an error

### ISSUE THREAD

**Issue by kinseii** [shalb/cluster.dev#284]
**Problem:**

During detailed analysis of the problem, it turned out that it's not a commenting problem, it's a problem in the presence of a hyphen in the variable: https://github.com/shalb/cluster.dev/issues/283
```
---
kind: Project
name: infrastructure
backend: default
variables:
  qwe-rty: 123
```
```
---
kind: Stack
name: qwerty-aks-us-1
template: ./qwerty/aks-us-1
backend: qwerty
variables:
  qwe-rty: {{ .project.variables.qwe-rty }}
```
```
[FATAL] Fatal error: load project configuration: load base configuration: loading project: searching for secrets in /****/infrastructure-cdev/stack.yaml: template: main:7: bad character U+002D '-'
```
**Cluster.dev Version:**
cdev version v0.9.5

**Comment by romanprog** [comment]
Hello,
This is a go-template limitation that also occurs in helm. There are different solutions. But it is not possible to change it in the cdev code.
Use like this:
```
kind: Stack
name: qwerty-aks-us-1
template: ./qwerty/aks-us-1
backend: qwerty
variables:
  qwe-rty: {{ index .project.variables "qwe-rty" }}
```
Also see 
https://stackoverflow.com/questions/63853679/helm-templating-doesnt-let-me-use-dash-in-names

**Comment by kinseii** [comment]
> Hello, This is a go-template limitation that also occurs in helm. There are different solutions. But it is not possible to change it in the cdev code. Use like this:
> 
> ```
> kind: Stack
> name: qwerty-aks-us-1
> template: ./qwerty/aks-us-1
> backend: qwerty
> variables:
>   qwe-rty: {{ index .project.variables "qwe-rty" }}
> ```
> 
> Also see https://stackoverflow.com/questions/63853679/helm-templating-doesnt-let-me-use-dash-in-names

Nice! Thank you!
