### ISSUE TITLE
Cli Installer

### ISSUE THREAD

**Issue by voatsap** [shalb/cluster.dev#54]
Based on design doc:
https://github.com/shalb/cluster.dev/blob/master/docs/design/cli-installer-design.md

And menu item samples:
https://github.com/shalb/cluster.dev/blob/master/install/cluster-dev.sh

Create cli installer tool.
I suppose we also need a separate "sample" repo in cluster.dev account, please let me know if you need to create some

**Comment by gelo22** [comment]
Aws policy added https://github.com/shalb/cluster.dev/blob/cli-installer/install/aws_policy.json

**Comment by gelo22** [comment]
Aws policy doc added https://github.com/shalb/cluster.dev/blob/cli-installer/docs/aws-iam-permissions.md

**Comment by voatsap** [comment]
Closed due to new desing
